#!/usr/bin/env ruby

# == Synopsis
#
# This is a MINARC command line tool that archives a given file. 
# If such file or a file with exactly same filename is already 
# archived in the system, an error will be raised.
# 
# 
# -f flag:
#
# Mandatory flag, stands for "--file".
# This option is used to specify the file to be archived. 
# File must be specified with the full path location.
#
# It is possible to include wildcards within the filename,
# for that purpose double quotes are required to avoid the shell
# to perform the substitution.
# -f "/full_path/file.*"
#
#
# -t flag:
#
# Mandatory flag, stands for "--type".
# This flag is used to specify the file-type of the file to be archived.
# By default MINARC will determine the file-type automatically, nevertheless 
# such classification may be overidden using this parameter. 
# In case MINARC fails to determine the file-type, it shall be specified by this flag. 
#
#
# -m flag:
#
# Optional flag, stands for "--move".
# This flag is used to "move" specified source file to the Archive.
# Source file location must be in the same Archive filesystem ($MINARC_ARCHIVE_ROOT).
# By default minArcStore.rb copies source file from the specified location and optionally
# once it is archived it deletes it (see "-d" flag). This flag is not compatible with -d & -H flags.
#
#
# -M flag:
#
# Optional flag, stands for "--Mutex".
# This flag is used to "Mutex" the execution of minArcStore:
# (e.g. usage of the bulk mode in the same directory).
#
#
# -d flag:
#
# Optional flag, stands for "--delete".
# This flag is used to delete specified source file upon a successful Archiving.
# If file is not archived successfully it is not deleted. This flag is not compatible with -m flag.
# 
#
# -U flag:
#
# Optional flag, stands for "--Unpack".
# This is the Unpack flag. It is used to unpack/decompress file before archiving it.
# The file format must be supported to perform the unpack action.
# The following formats are supported:
# - zip
# - tar
# - tgz
# - gz
#
#
# -H flag:
#
# Optional flag. This is the Hardlink flag. It is used to perform a Hardlink from the source file
# (specified with -f flag) to the Archive location . 
# Note that Archive and source file location must be in the same filesystem.
# This flag is not compatible with -d flag.
#
#
# -I flag:
#
# Optional flag, stands for "--Inventory".
# This flag is used to ONLY "inventory" the specified source file to the Archive.
# This is to leave untouched the source file and prevent subsequent storage into the Archive filesystem ($MINARC_ARCHIVE_ROOT)
# This flag is not compatible with any flag involving manipulation of source file or / and manipulation at the Archive storage.
#
#
# -a flag:
# Optional flag, stands for "--additional-fields".
# Allows to specify additional fields to fill in the archived_files table and the values
# to fill them with. Field names and values must be separated by ":".
#
#
# -T flag:
#
# Standalone flag, stands for "--Types".
# This flag is used to show all archived file-types.
# It is not compatible with any other flags and does not trigger the archiving process.
#
#
# -L flag:
#
# If location flag specifies a full_path, such path is used as the definitive location
# of the file archived ; if name does not refer to a full path, such destination is
# used by the plug-in handler to eventually use it to define the archive directory
#
#
# == Usage
# minArcStore -f <full_path_file> [-t type-of-the-file] [-d] [-L <full_path_location> | <suffix> ]
#     --noserver                 operations are performed locally
#     --file <full_path_file>    it specifies the file to be archived
#     --type <file-type>         it specifies the file-type of the file to be archived
#     --Location <path>|<suffix> it specifies the path desired archive location
#                                either it specifies the suffix used to build the final filename
#     --delete                   enable delete flag
#     --move                     it moves the file to the Archive
#     --update                   it updates the Archive with new file if previously present
#     --Unpack                   enable file unpacking for supported extensions
#     --additional-fields        allows to specify additional fields to fill in the archived_files table.
#     --Hardlink                 enables hardlinking the file to the archive.
#     --Types                    it shows all file-types archived
#     --Superbulk                Activates the superbulk mode
#     --Mutex                    Activates Mutex execution wrt supplied directory
#     --help                     shows this help
#     --Usage                    shows the usage
#     --Debug                    shows Debug info during the execution
#     --Profile                  shows execution time profiling information
#     --version                  shows version number
# 

require 'rubygems'
require 'getoptlong'
require 'rdoc'

require 'cuc/Log4rLoggerFactory'
require 'cuc/CheckerProcessUniqueness'

require 'arc/MINARC_Environment'
require 'arc/FileArchiver'
require 'arc/MINARC_Client'


# MAIN script function
def main

   include ARC

   @full_path_location     = nil
   @full_path_filename     = ""
   @filename               = ""
   @filetype               = ""
   @isDebugMode            = false
   @isProfileMode          = false
   @isSuperbulk            = false
   @bDelete                = false
   @bMove                  = false
   @bUnpack                = false
   bShowFileTypes          = false
   showVersion             = false
   @arrAddFields           = Array.new
   @bHardLink              = false
   @bUpdate                = false
   @bInventoryOnly         = false
   @bNoServer              = false
   @bShowVersion           = false
   @bShowUsage             = false
   @bMutex                 = false

   
   opts = GetoptLong.new(
     ["--file", "-f",               GetoptLong::REQUIRED_ARGUMENT],
     ["--type", "-t",               GetoptLong::REQUIRED_ARGUMENT],
     ["--Location", "-L",           GetoptLong::REQUIRED_ARGUMENT],
     ["--additional-fields", "-a",  GetoptLong::REQUIRED_ARGUMENT],
     ["--Mutex", "-M",              GetoptLong::NO_ARGUMENT],
     ["--noserver", "-n",           GetoptLong::NO_ARGUMENT],
     ["--Hardlink", "-H",           GetoptLong::NO_ARGUMENT],
     ["--Inventory", "-I",          GetoptLong::NO_ARGUMENT],
     ["--Types", "-T",              GetoptLong::NO_ARGUMENT],
     ["--delete", "-d",             GetoptLong::NO_ARGUMENT],
     ["--update", "-u",             GetoptLong::NO_ARGUMENT],
     ["--move", "-m",               GetoptLong::NO_ARGUMENT],
     ["--Debug", "-D",              GetoptLong::NO_ARGUMENT],
     ["--Profile", "-P",            GetoptLong::NO_ARGUMENT],
     ["--Superbulk", "-S",          GetoptLong::NO_ARGUMENT],
     ["--Unpack", "-U",             GetoptLong::NO_ARGUMENT],
     ["--Usage", "-g",              GetoptLong::NO_ARGUMENT],
     ["--version", "-v",            GetoptLong::NO_ARGUMENT],
     ["--help", "-h",               GetoptLong::NO_ARGUMENT]
     )
    
   begin
      opts.each do |opt, arg|
         case opt      
            when "--Debug"             then @isDebugMode          = true
            when "--noserver"          then @bNoServer            = true
            when "--Profile"           then @isProfileMode        = true
            when "--Superbulk"         then @isSuperbulk          = true
            when "--delete"            then @bDelete              = true
            when "--move"              then @bMove                = true
            when "--Mutex"             then @bMutex               = true
            when "--update"            then @bUpdate              = true
            when "--version"           then @bShowVersion         = true
	         when "--file"              then @full_path_filename   = arg.to_s
            when "--Location"          then @full_path_location   = arg.to_s
	         when "--type"              then @filetype             = arg.to_s
            when "--additional-fields" then @arrAddFields         = arg.to_s.split(":")
            when "--Types"             then bShowFileTypes        = true
			   when "--help"              then @bShowUsage           = true
	         when "--Usage"             then @bShowUsage           = true
            when "--Unpack"            then @bUnpack = true
            when "--Hardlink"          then @bHardLink = true
            when "--Inventory"         then @bInventoryOnly = true
         end
      end
   rescue Exception
      exit(99)
   end

   ## ------------------------------------------------------
   
   if @bShowVersion == true then
      print("\nminArc ", File.basename($0), " Version: [#{ARC::VERSION}]", "\n")
      hRecord = ARC::CHANGE_RECORD
      hRecord.each_pair{|key, value|
         puts "#{key} => #{value}"
      }
      exit(0)
   end

   ## ------------------------------------------------------

   ## ------------------------------------------------------

   if self.checkEnvironmentEssential == false then
      puts
      self.printEnvironmentError
      puts
      exit(99)
   end

   ## ------------------------------------------------------

   ## ------------------------------------------------------

   @archiveError           = ENV['MINARC_ARCHIVE_ERROR']
   @minArcConfigDir        = ENV['MINARC_CONFIG']
   checkDirectory(@archiveError)
   
   ## initialise the logger
   loggerFactory = CUC::Log4rLoggerFactory.new("ArcStore ", "#{@minArcConfigDir}/minarc_log_config.xml")
   
   if @isDebugMode then
      loggerFactory.setDebugMode
   end
      
   @logger = loggerFactory.getLogger
   
   if @logger == nil then
      puts
		puts "Could not initialize logging system !  :-("
      puts "Check minARC logs configuration under \"#{@minArcConfigDir}/minarc_log_config.xml\"" 
		exit(99)
   end

   ## ------------------------------------------------------


   if !ENV['MINARC_SERVER'] then
      @bNoServer   = true
   end


   if @bShowUsage == true then
      usage
      exit(0)
   end

   if @bDelete and @bMove then
      usage
      exit(66)
   end

   if @bHardLink and @bMove then
      usage
      exit(66)
   end

   if @bInventoryOnly and (@bDelete or @bMove or @bHardLink) then
      usage
      exit(66)
   end

   if @full_path_filename == "" then
      usage
      exit(66)
   end

   # -------------------------------------------------------

   if @bMutex == true then
      @locker = CUC::CheckerProcessUniqueness.new(File.basename($0), "", true, File.dirname(@full_path_filename)) 
      
      # @locker.setDebugMode
      
      if @locker.isRunning == true then
         # @locker.getAllRunningProcesses
         @logger.error("[ARC_675] Mutex of #{File.dirname(@full_path_filename)} not available for PID #{Process.pid}")
         exit(99)
      end  
   
      @locker.setRunning
   end

   # -------------------------------------------------------

   # if parameters are quoted to avoid variable expansion by shell
   if @full_path_filename.slice(0,1) == "\"" then
      @full_path_filename = @full_path_filename.dup.gsub!("\"","")
   end

   # -------------------------------------------------------

   if ENV['MINARC_SERVER'] and @bNoServer == false then
      @bRemoteMode = true
   else
      @bRemoteMode = false
      require 'arc/MINARC_DatabaseModel'
   end
 
   # -------------------------------------------------------
   #
   # show filetype
   #
   if bShowFileTypes then
      if @bRemoteMode == false then
         arrFiles = ArchivedFile.getFileTypes().sort
         arrFiles.each{|aFile|
            puts aFile.filetype
         }
         exit(0)
      else
         arc = ARC::MINARC_Client.new(@logger)
         
         if @isDebugMode == true then
            arc.setDebugMode
         end
         
         ret = arc.getAllFileTypes

         if ret == false
            puts "Could not get file-types from server"
            exit(99)
         else
            ret.split("\n").sort.each{|file| puts file}
            exit(0)
         end
      end
   end  
   
   # -------------------------------------------------------
   
   # ---------------------------------------------
   #
   # 20170603 - Bulk mode archive
   if @full_path_filename.include?("?") == true or @full_path_filename.include?("*") == true then
            
      if @isDebugMode == true then
         puts "Wildcard detected / bulk archiving"
      end
      
      if @isSuperbulk == true then
         superBulk
      else
         bulkArchive
      end
      exit(0)
   end
   # ---------------------------------------------
   
   if @full_path_filename.slice(0,1) != "/" then
      @full_path_filename = "#{Dir.pwd}/#{@full_path_filename.dup}"
   end

   if File.directory?(@full_path_filename) == true and @bUnpack == true then
      puts
      puts "Unpack flag cannot be used with a directory !"
      puts
      exit(99)
   end

   @filename = File.basename(@full_path_filename)

   # Check if it is a supported file for unpackaging 
   if @bUnpack == true then
      extension = File.extname(@filename).to_s.downcase
      bSupported = false
      case extension
         when ".zip"  then bSupported = true
         when ".tar"  then bSupported = true
         when ".gz"   then bSupported = true
         when ".tgz"  then bSupported = true
      end

      if bSupported == false then
         puts "#{fileName} is not supported for unpacking ! :-("
         puts
         exit(99)
      end
   end

   # Check the additional field list
   if @arrAddFields.size != 0 and @arrAddFields.size.modulo(2) != 0 then
      puts "Invalid additional-fields list ! :-("
      puts
      exit(99)
   end


   archiver  = ARC::FileArchiver.new(@bMove, @bHardLink, @bUpdate, @bInventoryOnly, @bNoServer, @logger)
   
   if @isDebugMode then
      archiver.setDebugMode
   end


   if @filetype == "" then
      puts "--type <file-type> is mandatory flag"
      puts
      exit(99)
   end

   ret = true
   
   if File.exist?(@full_path_filename) == false then
      @logger.error("[ARC_605] could not archive #{@filename}: #{@full_path_filename} does not exist ! #{'1F480'.hex.chr('UTF-8')}")
      exit(66)
   end
   
   begin      
      ret = archiver.archive(@full_path_filename, @filetype, @bDelete, @bUnpack, @arrAddFields, @full_path_location)
   rescue Exception => e
      @logger.error("[ARC_605] could not archive #{@filename}: #{e.to_s}")

      if File.exist?(@full_path_filename) == true then
         cmd      = "\\mv -f #{@full_path_filename} #{@archiveError}/"
         retVal   = system(cmd)
         @logger.warn("[ARC_340] Move to ArchiveError: #{cmd} | #{retVal}")
      end
      
      if @isDebugMode == true then
         puts
         puts e.backtrace
         puts
      end
      
      exit(66)
   end
   
   if ret == false then
      puts
      puts "MINARC could not archive #{@filename}"
      puts
      exit(99)
   end
 
   if @bMutex == true then
      @locker.release
   end
 
   exit(0)

end

## -----------------------------------------------------------


def superBulk
   if @isDebugMode == true then
      puts
      puts "superbulk mode detected"
   end
   
   archiver  = ARC::FileArchiver.new(@bMove, @bHardLink, @bUpdate, @bInventoryOnly, @bNoServer, @logger)
   
   if @isDebugMode then
      archiver.setDebugMode
   end

   if @isProfileMode then
      archiver.setProfileMode
   end

   retVal = true

   arrFiles = Dir[@full_path_filename]
   
   retVal = archiver.bulkarchive(arrFiles, @filetype, @bDelete, @bUnpack, @arrAddFields, @full_path_location)
      
   if retVal == true then
      exit(0)
   else
      exit(1)
   end
   
end


## -------------------------------------------------------------

def bulkArchive
   if @isDebugMode == true then
      puts
      puts "bulk mode detected"
   end
   
   archiver  = ARC::FileArchiver.new(@bMove, @bHardLink, @bUpdate, @bInventoryOnly, @bNoServer, @logger)
   
   if @isDebugMode then
      archiver.setDebugMode
   end

   if @isProfileMode then
      archiver.setProfileMode
   end


   retVal = true

   arrFiles = Dir[@full_path_filename]
   
   arrFiles.each{|file|
      
      if @isDebugMode == true then
         puts "found #{file}"
      end
      
      arrFile = Array.new
      
      arrFile << file
      arrFile << @filetype
      arrFile << @full_path_location
      arrFile << Time.now
      
      begin
         ret = archiver.archive(file, @filetype, @bDelete, @bUnpack, @arrAddFields, @full_path_location)
   
         if ret == false then
            retVal = false
            @logger.error("[ARC_666] Could not archive #{file}")
            next
         end
      rescue Exception => e
         @logger.error("[ARC_666] Could not archive #{file} / #{e.to_s}")
         if @isDebugMode == true then
            puts
            puts e.backtrace
            puts
         end
                  
         if File.exist?(file) == true then
            cmd      = "\\mv -f #{file} #{@archiveError}/"
            retVal   = system(cmd)
            @logger.warn("[ARC_340] Move to ArchiveError: #{cmd} | #{retVal}")
         end

         next
      end
   }
   
   if retVal == true then
      exit(0)
   else
      exit(1)
   end
   
end
## -------------------------------------------------------------

def usage
   fullpathFile   = File.expand_path(__FILE__)
   value          = `#{"head -123 #{fullpathFile}"}`
      
   value.lines.drop(1).each{
      |line|
      len = line.length - 1
      puts line[2, len]
   }
end
## -------------------------------------------------------------


## ===============================================================================
## Start of the main body
##
main
##
## End of the main body
## ===============================================================================
