#!/usr/bin/env ruby

#########################################################################
###
### === Ruby source for #MINARC_TestCasesOData class
###
### === Written by DEIMOS Space S.L. (bolf)
###
### === Mini Archive Component (MinArc)
### 
### module MINARC
###
#########################################################################

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'cuc/Log4rLoggerFactory'

require 'ctc/WrapperCURL'

require 'arc/MINARC_Environment'
require 'arc/MINARC_Client'
require 'arc/MINARC_Status'
require 'arc/ReadMinarcConfig'
require 'arc/MINARC_API_OData'
      
### rake -f build_minarc.rake minarc:install[borja,localhost,s2_test_pg]

# Preconditions:
# 1 - setup 
# 1.1 - load_config_development
# 1.2 - inventory database is created

# 2 - teardown
# 2.1 - purge archive
# 2.2 - inventory database is destroyed

## 0  - test_local_minArcStore
## 1  - test_odata_download
## 2  - test_odata_query_name
## 3  - test_odata_query_date
## 4  - test_odata_query_validity_date
## 5  - test_odata_query_count
## 6  - test_odata_query_count_name
## 7  - test_odata_query_skip
## 8  - test_odata_query_top
## 9  - test_odata_query_expand

class TestCaseStore < Test::Unit::TestCase

   include CTC::WrapperCURL

   include CUC::DirUtils
   include ARC
   include ARC_ODATA

   # Order of the test cases execution according to defintion within code
   self.test_order = :defined
   
   # --------------------------------------------------------
   
   Test::Unit.at_start do      
      
      system("clear")
      
      puts
      puts "======================================"
      puts "MINARC OData Unit Test Cases"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      c = STDIN.getc
            
      if c != 'Y' then
         exit(99)
      end
      
      @@conf = MINARC_Environment.new
      
      @@conf.wrapper_load_config


      puts      
      @@conf.wrapper_print_environment
      puts
 
      ## Mixin does not work !!!!!
      ## checkDirectory(ENV["MINARC_ARCHIVE_ROOT"])
      system("mkdir -p /tmp/minarc/archive_root")
      system("mkdir -p /tmp/minarc/tmp")
 
      if @@conf.wrapper_check_environment == false then
         puts "minArc environment not suited for unit tests"
         puts
         exit(99)
      end
 
#      puts "call start teardown"
#      self.teardown
#      puts "call end teardown"


      begin
         cmd = "minArcDB -d"
         puts cmd
         ret = system(cmd)

         cmd = "minArcDB -c"
         puts cmd
         ret = system(cmd)
         
         cmd = "minArcDB -a test:test"
         puts cmd
         ret = system(cmd)
         
      rescue Exception => e
      end

      begin
         cmd = "minArcPurge -Y"
         puts cmd
         # ret = system(cmd)
      rescue
      end



=begin
      puts
      puts "GEM DATADIR = #{Gem.datadir("minarc")}"
      puts
      
      rootpath = nil
      
      if Gem.datadir("minarc") == nil then
         rootpath = ENV['DEC_BASE']
         @testDir = File.join(rootpath, "code/arc/plugins/test/")
      else
         rootpath = Gem.datadir("minarc")
         @testDir = File.join(rootpath, "../../code/arc/plugins/test/")
      end
      
=end
      
      @@testDataDir        = File.join( File.dirname(File.expand_path(__FILE__)), "plugins/test" )
      @@testFile1          = "S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.EOF"
      @@testFile2          = "S2B_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.EOF"
      @@filename1_noext    = "S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001"
      @@filename2_noext    = "S2B_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001"
      @@errorZone          = ENV['MINARC_ARCHIVE_ERROR']

      system("rm -f #{@@testDataDir}/S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z")
      system("rm -f #{@@testDataDir}/20110204T193316_000001.m2ts")

      @@prevDir = Dir.pwd     
      Dir.chdir(@@testDataDir)
      system("echo \'S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001\' > S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.EOF")
      system("echo \'S2B_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001\' > S2B_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.EOF")
      Dir.chdir(@@prevDir)

      system("minArcServer -k")
      prevDir = Dir.pwd
      Dir.chdir(ENV['MINARC_TMP'])
      
            
      puts "init server"
      FileUtils.rm_f("#{ENV['MINARC_TMP']}/minarc_server.out")
      # @serverPID = spawn("minArcServer -s > #{ENV['MINARC_TMP']}/minarc_server.out 2>&1")
      @serverPID = spawn("minArcServer -s > #{ENV['MINARC_TMP']}/minarc_server.out 2>&1")
      Dir.chdir (prevDir)
      puts @serverPID

      sleep(2.0)

      @@arrInputFiles = [ \
                           "S2__OPER_SRA_EDRS_A_PDMC_20180719T030000_V20180719T030000_20180831T233257.EOF", \
                           "S2B_OPER_REP_OPDPC__SGS__20180721T061746_V20180721T061746_20180721T061746.EOF", \
                           "S2B_OPER_REP_OPDPC__MPC__20180721T061746_V20180721T061746_20180721T061746.EOF", \
                           "S2__OPER_REP_ARC____EPA__20180721T110140_V20180721T085229_20180721T085414.EOF", \
                           "S2__OPER_REP_ARC____MPC__20180721T110140_V20180721T085229_20180721T085414.EOF", \
                           "S2__OPER_REP_OPAI___EPA__20180721T130012_V20180721T010002_20180721T130001.EOF", \
                           "S2__OPER_REP_OPAI___MPC__20180721T130012_V20180721T010002_20180721T130001.EOF", \
                           "S2A_OPER_MPL__NPPF__20180720T110000_20180806T140000_0001.TGZ", \
                           "S2__OPER_REP_OPLTAS_UPA__20180722T060002_V20180721T030002_20180722T060002.EOF", \
                           "S2A_OPER_MPL__NPPF__20180820T110000_20180906T140000_0001.TGZ", \
                           "S2A_OPER_MPL__NPPF__20190420T110000_20190426T140000_0001.TGZ", \
                           "S2A_OPER_MPL__NPPF__20170820T110000_20170906T140000_0001.TGZ", \
                           "S2A_OPER_MPL__NPPF__20180920T110000_20180926T140000_0001.TGZ", \
                           "S2A_OPER_MPL__NPPF__20190520T110000_20190526T140000_0001.TGZ", \
                           "S2A_OPER_MPL_ORBPRE_20180720T030221_20180730T030221_0001.EOF", \
                           "S2A_OPER_REP_PASS_E_EDRS_20180720T235700_V20180720T234817_20180720T235645.EOF", \
                           "S2A_OPER_REP_STNACQ_SGS__20180724T123414_V20180724T120243_20180724T121539.EOF", \
                           "S2A_OPER_MPL_SPMPS__PDMC_20180719T090005_V20180720T090000_20180726T090000.EOF", \
                           "S2A_OPER_MPL_FSSGS__PDMC_20180719T090008_V20180720T090000_20180726T090000.EOF", \
                           "S2__OPER_REP_OPLTA__EPA__20180721T130015_V20180721T010002_20180721T130001.EOF", \
                           "S2__OPER_REP_OPLTAS_UPA__20190522T060002_V20190521T030002_20190522T060002.EOF", \
                           "S2__OPER_GIP_PROBA2_MPC__20190502T000212_V20190506T004000_21000101T000000_B00.TGZ", \
                           "S2A_OPER_GIP_PROBAS_MPC__20190307T000207_V20190311T000000_21000101T000000_B00.TGZ", \
                           "S2__OPER_REP_OPDAM1_PDMC_20180721T110501_V20180721T085229_20180721T085229.EOF" \
                           ]
                       
                       
      @@arcConfigDir = File.join(File.dirname(File.expand_path(__FILE__)), "../../config")
      puts
      puts @@arcConfigDir
      puts                   
      ## ----------------------------------
      ## initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("ARCTEST", "#{@@arcConfigDir}/minarc_log_config.xml")
   
      @@logger = loggerFactory.getLogger   
      if @@logger == nil then
         puts
		   puts "Error in OrchestratorIngester::initialize"
     	   puts "Could not initialize logging system !  :-("
         puts "Check minARC logs configuration under \"#{@@arcConfigDir}/minarc_log_config.xml\"" 
 	      puts
   	   exit(99)
      end

            
   end
   
   # --------------------------------------------------------
   
   Test::Unit.at_exit do
#       puts "End of tests"
#             
#       puts "Killing MINARC_Server"
#       cmd = "minArcServer -k"
#       system(cmd)
#       
#       Process.kill(9, @serverPID)
            
   end
   
   # --------------------------------------------------------   
   
   # Setup before every test-case
   #
   def setup
      puts __method__.to_s
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      system("\\rm -rf /tmp/minarc_log_file*.log")
      
      cmd = "minArcPurge -Y"
      ret = system(cmd)

      if ret == false then
         puts "Error when cleaning the minarc root directory ! :-("
         puts
         exit(99)
      end

      
      @path = "#{ENV['MINARC_BASE']}/code/arc"
      
      Dir.chdir(@@testDataDir)
      system("echo \'S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001\' > S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.EOF")
      system("\\rm -f #{@@testDataDir}/#{@@filename1_noext}.7z")
      
      Dir.chdir(@@prevDir)    

      puts
      puts Dir.pwd
      puts
      puts "END OF MINARC_UnitTests::#{__method__.to_s}"
      puts
   end
   # --------------------------------------------------------
   # After every test case

   def teardown
      puts __method__.to_s
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      puts
      puts "END OF MINARC_UnitTests::#{__method__.to_s}"
      puts

   end
   ## ------------------------------------------------------

   ## -----------------------------------------------------------
   ##
   ## 
   def test_local_minArcStore
      puts __method__.to_s
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      system("mkdir -p /tmp/minarc/tmp/")
      
      cmd = "cp #{@@testDataDir}/#{@@testFile1} /tmp/minarc/tmp/"
      puts cmd
      system(cmd)

      cmd = "cp #{@@testDataDir}/#{@@testFile2} /tmp/minarc/tmp/"
      puts cmd
      system(cmd)
      
      cmd = "minArcStore -t S2PDGS -f /tmp/minarc/tmp/#{@@testFile1} --noserver -d -D"
      puts cmd
      assert(system(cmd), "minArcStore")
 
      cmd = "minArcStore -t S2PDGS -f /tmp/minarc/tmp/#{@@testFile2} --noserver -d -D"
      puts cmd
      assert(system(cmd), "minArcStore")
     
      system("\\rm -f /tmp/minarc/tmp/#{@@filename1_noext}.7z")
      system("\\rm -f /tmp/minarc/tmp/#{@@filename2_noext}.7z")
   end
   ## ------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_download
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
       
      url = "localhost:4567/odata/v1/Products"
   
      ## -------------------------------
      
      if File.exist?("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z") == true
         File.delete("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z")
      end

      ## -------------------------------
      ## well-formed download request
      uuid = "1234-acds-22e2e121e"

      cmd = "curl -v -u test:test \'#{url}(#{uuid})/\$value\' "
      puts cmd
      system(cmd)
      ## -------------------------------

      ## -------------------------------
      ## well-formed unsupported request / bad request
      uuid = "1234-acds-22e2e121e"

      cmd = "curl -v -u test:test \'#{url}(#{uuid})/\$count\' "
      puts cmd
      system(cmd)
      ## -------------------------------

      ## store a test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------
   
      ## -------------------------------
      ## well-formed download request / good request
#      cmd = "curl -v -u test:test \'#{url}(#{uuid})/\$value\' "
#      puts cmd
#      ret = system(cmd)      
#      assert(ret, "successful curl download")
      
      if File.exist?("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z") == true
         File.delete("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z")
      end
      
      theURL = "#{url}(#{uuid})/\$value"
      ret = getFile(theURL, "test", "test", "thefile", true)
      
      assert(ret, "File download with WrapperCURL.getFile")
      
      if File.exist?("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z") == true
         File.delete("S2A_OPER_REP_OPDPC__SGS__21000101T000000_V21000101T000000_21000101T000001.7z")
      end

      ## -------------------------------
   
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_name
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store a test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / bad function request
      cmd = "curl -v -u test:test \'#{url}$filter=notsupportedfunction(Name,'S2')' "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / bad property request
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(File,'S2')' "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      
      ## -------------------------------

   
      ## -------------------------------
      ## well-formed query request / good request
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
          
      ## -------------------------------
 
      ## -------------------------------
      ## well-formed query request / good request with no results
      cmd = "curl -v -u test:test \'#{url}$filter=endswith(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
          
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / good request with results
      cmd = "curl -v -u test:test \'#{url}$filter=endswith(Name,'21000101T000001')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
          
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / good request
      cmd = "curl -v -u test:test \'#{url}$filter=contains(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
          
      ## -------------------------------

  
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_date
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate lt 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$filter=PublicationDate%20lt%202020-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate le 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$filter=PublicationDate%20le%202020-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate gt 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$filter=PublicationDate%20gt%202020-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate ge 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$filter=PublicationDate%20ge%202020-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 


      ## https://<service-root-uri>/odata/v1/Products?$filter=ContentDate/Start gt 2019-05-15T00:00:00.000Z and ContentDate/End lt 2019-05-16T00:00:00.000Z
  
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_validity_date
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=ContentDate/Start gt 2019-05-15T00:00:00.000Z
            
      cmd = "curl -v -u test:test \'#{url}$filter=ContentDate/Start%20gt%202019-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=ContentDate/End le 2119-05-15T00:00:00.000Z
            
      cmd = "curl -v -u test:test \'#{url}$filter=ContentDate/End%20le%202119-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request with start > end which should never return results
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=ContentDate/Start gt 2119-05-15T00:00:00.000Z and ContentDate/End lt 2119-05-16T00:00:00.000Z

            
      cmd = "curl -v -u test:test \'#{url}$filter=ContentDate/Start%20gt%202119-05-15T00:00:00.000Z%20and%20ContentDate/End%20lt%202119-05-16T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------

      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 


   end
   ## -----------------------------------------------------------
   ## -----------------------------------------------------------
   ##
   ## https://<service-root-uri>/odata/v1/Products?$count=true

   def test_odata_query_count
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request
      
      ## https://<service-root-uri>/odata/v1/Products?$count=true
      
      cmd = "curl -v -u test:test \'#{url}Products?$count=true' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 

   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------
   ##
   ## /odata/v1/Products$count=true&$filter=startswith(Name,'S2A')

   def test_odata_query_count_name
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request with negative results
      
      ## https://<service-root-uri>/odata/v1/Products$count=true&$filter=startswith(Name,'S1B')
      
      cmd = "curl -v -u test:test \'#{url}Products?$count=true\&$filter=startswith(Name,'S1B')' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request with positive results
      
      ## https://<service-root-uri>/odata/v1/Products$count=true&$filter=startswith(Name,'S2B')
      
      cmd = "curl -v -u test:test \'#{url}Products?$count=true\&$filter=startswith(Name,'S2B')' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request with positive results
      
      ## https://<service-root-uri>/odata/v1/Products$count=true&$filter=startswith(Name,'S2A')
      
      cmd = "curl -v -u test:test \'#{url}Products?$count=true\&$filter=startswith(Name,'S2A')' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request request with positive results
      
      ## https://<service-root-uri>/odata/v1/Products$count=true&$filter=startswith(Name,'S2')
      
      cmd = "curl -v -u test:test \'#{url}Products?$count=true\&$filter=startswith(Name,'S2')' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 

   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_skip
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store a test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / skip 1 item / 0 items left
      cmd = "curl -v -u test:test \'#{url}$skip=1\&$filter=startswith(Name,'S2A')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / skip 1 item / 0 items left
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2B')\&$skip=1' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / skip 1 item
      cmd = "curl -v -u test:test \'#{url}$skip=1\&$filter=startswith(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / skip 1 item
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2')\&$skip=1' | jq "
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query date request request / skip 1 item
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate gt 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$skip=1\&$filter=PublicationDate%20gt%202020-05-15T00:00:00.000Z' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query date request request / skip 1 item
      
      ## https://<service-root-uri>/odata/v1/Products?$filter=PublicationDate gt 2020-05-15T00:00:00.000Z
      
      cmd = "curl -v -u test:test \'#{url}$filter=PublicationDate%20ge%202020-05-15T00:00:00.000Z\&$skip=1' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------

      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 

  
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_top
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store a test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / top 1 item
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2')\&$top=1' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request changing order / top 1 items
      cmd = "curl -v -u test:test \'#{url}$top=1\&$filter=startswith(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / top 1 item
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2')\&$top=2' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / skip 1 + top 1 item
      cmd = "curl -v -u test:test \'#{url}$skip=1\&$filter=startswith(Name,'S2')\&$top=1' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / top 1 + skip 1 item
      cmd = "curl -v -u test:test \'#{url}$top=1\&$skip=1\&$filter=startswith(Name,'S2')' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / top 1 + skip 1 item
      cmd = "curl -v -u test:test \'#{url}$top=1\&$filter=startswith(Name,'S2')\&$skip=1' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------
      ## well-formed query request / skip 1 + top 2 item => replies just one
      cmd = "curl -v -u test:test \'#{url}$skip=1\&$filter=startswith(Name,'S2')\&$top=2' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / skip 2 + top 2 item => no replies
      cmd = "curl -v -u test:test \'#{url}$skip=2\&$filter=startswith(Name,'S2')\&$top=2' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request / skip 1 + top 2 item => replies just one
      cmd = "curl -v -u test:test \'#{url}$filter=startswith(Name,'S2')\&$top=2\&$skip=1' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------

      arr = Dir["/tmp/minarc_log_file*.log"]
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 

  
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def test_odata_query_expand
      puts
      puts "================================================"
      puts "MINARC_UnitTests::#{__method__.to_s}"
      puts
      
      cmd = "minArcDB -d"
      puts cmd
      system(cmd)

      cmd = "minArcDB -c"
      puts cmd
      assert(system(cmd), "minArcDB first time")
 
      cmd = "minArcDB -a test:test -D"
      puts cmd
      assert(system(cmd), "created used test")

      cmd = "minArcServer -k"
      puts cmd
      assert(system(cmd), cmd)

      puts

      cmd = "minArcServer -s -D"
      #cmd = "minArcServer -s"
      puts cmd
      assert(spawn(cmd), cmd)
 
      sleep(5.0)
      
      cmd = "minArcServer -c"
      puts cmd
      assert(system(cmd), cmd)
      puts
        
      cmd = ""

      config = ReadMinarcConfig.instance   
      server = config.getArchiveServer
      
      
      url = "#{server}#{ARC_ODATA::API_URL_PRODUCT_QUERY}"
   
      ## -------------------------------
      
      ## store a test file
      test_local_minArcStore

      cmd = "minArcStatus -f #{File.basename(@@testFile1, ".*")} --noserver | jq .uuid"
      ret = `#{cmd}`
      puts cmd
      puts 
      uuid =  ret.chop.gsub("\"","")
      assert($?.exitstatus, "Retrieving the uuid")
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request but not recognized entity
      cmd = "curl -v -u test:test \'#{url}$expand=Donald' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------

      ## -------------------------------
      ## well-formed query request 
      cmd = "curl -v -u test:test \'#{url}$expand=Attributes' | jq"
      puts cmd
      ret = system(cmd)      
      assert(ret, "successful curl query")
      
      ## -------------------------------


      ## -------------------------------

      arr = Dir["/tmp/minarc_log_file*.log"]

      cmd = "grep ARC_777 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 
      
      cmd = "grep ARC_210 #{arr[0]}"
      puts cmd
      assert(system(cmd), "see query traces #{__method__.to_s}") 

  
   end
   ## -----------------------------------------------------------

end


# =====================================================================

