#!/bin/bash
#
# Script to review inputs from the PDGS
# Author: Daniel Brosnan Blazquez

# Intray of the E2ESPM

INGESTION_TIME=`date +%Y%m%dT%H%M%S`

XMLFILE="S2__REP_ARC_TCI_$INGESTION_TIME.xml"

FILES=/home/e2edc/data/intray/REP_ARC_TCI/*.EOF

echo '<list_of_tci>' >> $XMLFILE

for file in $FILES
do
   # echo "processing $file"
   tci_name=$(xml_grep --text_only 'archive:Pdi-id' $file)
   tci_size=$(xml_grep --text_only 'Data_Size' $file)
   # echo $tci_name, $tci_size
   echo '<tci><name>'"$tci_name"'</name><size>'"$tci_size"'</size></tci>' >> $XMLFILE
   # mv $file "$file.bckp"
   rm $file
done

echo '</list_of_tci>' >> $XMLFILE

mv $XMLFILE /Data_Disk/e2espm/data/interfaces/s2pdgs/pre_input/
