#!/usr/bin/env bash

#########################################################################
#
# ===       
#
# === Written by Borja Lopez Fernandez
#
# === Casale & Beach
# 
#
#
#########################################################################

export METEO_BASE=$HOME/Projects/weather
export METEO_TEMP=$HOME/Projects/weather/data/temp

# Define HOME to startup meteo station with root at boot time
# export HOME=/home/meteo

. $HOME/Projects/dec/config/./profile_common
. $HOME/Projects/dec/config/./profile_ddc
. $HOME/Projects/dec/config/./profile_dcc
. $HOME/Projects/dec/config/./profile_ws23rb
. $HOME/Projects/dec/config/./profile_wstation
. $HOME/Projects/dec/config/./profile_minarc
. $HOME/Projects/dec/config/./profile_esa
. $HOME/Projects/dec/config/./profile_jenkins
