#!/usr/bin/env bash

#########################################################################
#
# ===       
#
# === Written by Borja Lopez Fernandez
#
# === Casale & Beach
# 
#
#
#########################################################################

. $HOME/Projects/dec/config/./profile_common

export DDC_ARCHIVE_ROOT=$HOME/Projects/weather/data/outbox
export PATH=$PATH:$DEC_BASE/code/ddc
