#!/usr/bin/env bash

#########################################################################
#
# ===       
#
# === Written by Borja Lopez Fernandez
#
# === Casale & Beach
# 
#
#
#########################################################################

. $HOME/Projects/dec/config/./profile_common

export PATH=$PATH:$DEC_BASE/code/dcc
