#########################################################################
#
# Git:
#     Dockerfile.orc.sqlite3  $minarc    $Author: bolf$
#                             $Date: 2018-11-15T16:49:35+01:00$ 
#                             $Committer: bolf$
#                             $Hash: f3afa7c$
#
#########################################################################

FROM ruby:2.4.1-slim

# ================================================

# ================================================

# RUN apt-get update && apt-get install -y net-tools

RUN apt-get update && \
  apt-get install -y --no-install-recommends build-essential gcc make p7zip-full sqlite3 libsqlite3-dev exiftool curl lsof

# ------------------------------------------------
    
# ================================================

# MINARC Environment Variables into a single layer

ENV   RACK_ENV=production \
      ORC_DB_ADAPTER=sqlite3 \
      ORC_DATABASE_NAME=/home/vagrant/Volumes/orc_inventory
      ORC_DATABASE_USER=root \
      ORC_DATABASE_PASSWORD=1mysql \
      ORC_CONFIG=/home/vagrant/Volumes/orc_config \
      ORC_TMP=/tmp/orc_tmp \
      MINARC_VERSION=DEPRECATED_VARIABLE \
      MINARC_SERVER=http://localhost:4567 \
      MINARC_DB_ADAPTER=sqlite3 \
      MINARC_DATABASE_USER=root \
      MINARC_DATABASE_PASSWORD=1mysql \
      DEC_TMP=/home/vagrant/Volumes/0.tmp \
      TMP_DIR=/home/vagrant/Volumes/0.tmp \
      MINARC_TMP=/home/vagrant/Volumes/0.tmp \
      MINARC_ARCHIVE_ROOT=/home/vagrant/Volumes/orc_archive \
      MINARC_ARCHIVE_ERROR=/home/vagrant/Volumes/orc_error \
      MINARC_DATABASE_NAME=/home/vagrant/Volumes/minarc_inventory

RUN env
# ================================================

# MINARC ROOT storage to be handled as data volumes

# It seems better to avoid unnamed volumes

# RUN mkdir /volume
# VOLUME /volume
# 
# at volume management, minarc initialisation is required: minArcDB -c

ENV PORT 4567
EXPOSE 4567

# ------------------------------------------------
# Install ruby gem dependencies
COPY Gemfile .
RUN bundle install
# ------------------------------------------------

# ================================================

# Install the minarc gem

COPY ./gems/minarc.gem .
RUN gem install --local minarc.gem
# ------------------------------------------------

# Install the orc gem

COPY ./gems/orc.gem .
RUN gem install --local orc.gem
# ------------------------------------------------



# Execution entry point

# CMD ["minArcServer", "-s"]

CMD ["minArcServer", "-s"]

# ------------------------------------------------


