#########################################################################
#
# Git:
#     Dockerfile.orc.sqlite3  $minarc    $Author: bolf$
#                             $Date: 2018-11-15T16:49:35+01:00$ 
#                             $Committer: bolf$
#                             $Hash: f3afa7c$
#
#########################################################################

FROM ruby:2.4.1-slim

# ================================================

# ================================================

# RUN apt-get update && apt-get install -y net-tools

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update && \
  apt-get install -y --no-install-recommends build-essential gcc make p7zip-full zip unzip sqlite3 libsqlite3-dev exiftool curl lsof

# ------------------------------------------------
    
# ================================================

RUN env
# ================================================

# MINARC ROOT storage to be handled as data volumes

# It seems better to avoid unnamed volumes

# RUN mkdir /volume
# VOLUME /volume
# 
# at volume management, minarc initialisation is required: minArcDB -c

ENV PORT 4567
EXPOSE 4567

# ------------------------------------------------
# Install ruby gem dependencies
COPY Gemfile .
RUN bundle install
# ------------------------------------------------

# ================================================

# Install the minarc gem

COPY ./gems/minarc.gem .
RUN gem install --local minarc.gem
# ------------------------------------------------

# Install the orc gem

COPY ./gems/orc.gem .
RUN gem install --local orc.gem
# ------------------------------------------------

COPY orc_test.env .
COPY orc_test.bash .

COPY minarc_test.env .
COPY minarc_test.bash .

# ------------------------------------------------


