# Data Exchange Component / Minimum Archive
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'activerecord', '5.2.3'
gem 'activerecord-import', '0.20.2'
gem 'bcrypt'
# gem 'curb'
gem 'exiftool'
gem 'filesize', '0.1.1'
gem 'ftools'
gem 'ftpfxp'
gem 'geokit'
gem 'json'
gem 'log4r', '1.1.10'
gem 'mini_exiftool'
gem 'net-sftp', '2.1.2'
gem 'net-ssh', '4.2.0'
# gem 'pg'
gem 'sequel'
gem 'sinatra', '2.0.0'
gem 'sinatra-contrib', '2.0.0'
gem 'sqlite3'
gem 'test-unit', '3.2.3'
gem 'thin'
gem 'writeexcel'

# ------------------------------------------------
# group :development do
#    gem 'sqlite3'
# end
# ------------------------------------------------

# ------------------------------------------------
# group :production do 
#    gem 'pg'
# end
# ------------------------------------------------
