# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|

#
# Vagrant is now only used for hosting containers
# and no component is directly installed there
#
#
#   # ----------------------------------------------------------------------
#   # install bundler with vagrant non-root user
#   $script_bundler = <<-SCRIPT
#   cd /vagrant
#   bundle install --clean --force
#   SCRIPT
#   # ----------------------------------------------------------------------
#
#   # ----------------------------------------------------------------------
#   # gem install with vagrant non-root user
#   $script_minarc = <<-SCRIPT
#   gem install --local /vagrant/minarc.gem
#   SCRIPT
#   # ----------------------------------------------------------------------


  
   config.vm.define "minarc-server" do |minarc_server|
      # minarc_server.vm.box         = "hashicorp/precise64"
      
      minarc_server.vm.box          = "ubuntu/trusty64"
      
      minarc_server.vm.hostname     = "vagrant"
      
      minarc_server.vm.boot_timeout = 400
      
      minarc_server.vm.network "forwarded_port", guest: 4567, host: 4567, host_ip: "127.0.0.1"
      
      
      # minarc_server.vm.box_check_update = false
      # minarc_server.vm.network "private_network", ip: "192.168.50.1"
            
      minarc_server.vm.synced_folder "/Users/borja/Projects/dec/config/", "/home/vagrant/minarc_config", disabled: false
      
      # --------------------------------------------------------------
      #
      # Provisioning section
      
      minarc_server.vm.provision :shell, path: "bootstrap.sh"
      
      minarc_server.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
      
      minarc_server.vm.provision :shell, path: "install-ruby.sh", args: "2.4 rails haml", privileged: false
      
      # minarc_server.vm.provision :shell, inline: $script_bundler, privileged: false
      
      # minarc_server.vm.provision :shell, inline: $script_minarc, privileged: false
      
      # --------------------------------------------------------------
   
   end


#   config.vm.define "minarc-client", autostart: false do |minarc_client|
#      
#      # minarc_client.vm.box         = "hashicorp/precise64"
#      minarc_client.vm.box         = "ubuntu/trusty64"
#      
#      minarc_client.vm.hostname    = "minarc-client"
#
#      # --------------------------------------------------------------
#      #
#      # Provisioning section
#      
#      minarc_client.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
#      
#      minarc_client.vm.provision :shell, path: "install-ruby.sh", args: "2.4 haml", privileged: false
#      
#      # minarc_client.vm.provision :shell, inline: $script_bundler, privileged: false
#      
#      # --------------------------------------------------------------
#      
#   end

  
end



# ==============================================================================



