#########################################################################
#
# Git:
#     Vagrantfile          $Author: bolf$
#                          $Date$ 
#                          $Committer: bolf$
#                          $Hash: f3afa7c$
#                          $Subject$
#
#########################################################################


# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|

#
# Vagrant is now only used for hosting containers
# and no component is directly installed there
#
#
   # ----------------------------------------------------------------------
   # install bundler with vagrant non-root user
   $script_bundler = <<-SCRIPT
   cd /vagrant
   bundle install --clean --force
   SCRIPT
   # ----------------------------------------------------------------------

   # ----------------------------------------------------------------------
   # gem install with vagrant non-root user
   $script_minarc = <<-SCRIPT
   gem install --local /vagrant/gems/minarc.gem
   SCRIPT
   # ----------------------------------------------------------------------


  
   config.vm.define "vagrantbox" do |vagrantbox|
      
      vagrantbox.vm.box_check_update = false
      
      # vagrantbox.vm.box        = "hashicorp/precise64"
      
      vagrantbox.vm.box          = "ubuntu/trusty64"
      
      vagrantbox.vm.hostname     = "vagrantbox"
      
      vagrantbox.vm.boot_timeout = 400
      
      vagrantbox.vm.network "public_network"
      
      vagrantbox.vm.network "forwarded_port", guest: 4567, host: 4567 #, host_ip: "127.0.0.1" #, auto_correct: true
                 
      vagrantbox.vm.synced_folder "/Users/borja/Volumes", "/home/vagrant/Volumes", disabled: false

      
      # --------------------------------------------------------------
      #
      # Provisioning section
      
      vagrantbox.vm.provision :shell, path: "bootstrap.sh"
      
      vagrantbox.vm.provision :shell, path: "install-rvm.sh", args: "stable", privileged: false
      
      vagrantbox.vm.provision :shell, path: "install-ruby.sh", args: "2.4 rails haml", privileged: false
      
      vagrantbox.vm.provision :shell, inline: $script_bundler, privileged: false
      
      vagrantbox.vm.provision :shell, inline: $script_minarc, privileged: false
      
      # --------------------------------------------------------------
   
   end
  
end



# ==============================================================================



