#########################################################################
#
# Git:
#     Dockerfile.dec.s2.test_s2pdgs.test_s2pdgs  
#                          $Author: bolf$
#                          $Date: 2018-11-13T11:54:43+01:00$ 
#                          $Committer: bolf$
#                          $Hash: f3afa7c$
#
#########################################################################
#
# Dockerfile for AUXIP
#
# Execution point from project root directory
#
FROM ruby:2.6
# ================================================
RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y --no-install-recommends \
    supervisor \
    build-essential \
    net-tools \
    lftp \
    ftp \
    libxml2 \
    xml-twig-tools \
    gnupg \
    net-tools \
    gcc \
    make \
    p7zip-full \
    sqlite3 \
    libsqlite3-dev \
    exiftool \
    ncftp \
    curl \
    lsof
RUN apt-get update \
  && apt-get install -y postgresql postgresql-contrib \
  && apt-get install sudo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN apt-get update && \
      apt-get install -y apt-file && \
      apt-file update && \
      apt-get install -y vim
# ------------------------------------------------
RUN groupadd -g 10001 e2edc && \
    useradd -u 10001 -ms /bin/bash -g e2edc -d /home/e2edc e2edc
# ------------------------------------------------
COPY ./install/scripts/entrypoint_dec_s2_e2espm-inputhub_e2edc.sh /usr/bin/
RUN ln -s /usr/bin/entrypoint_dec_s2_e2espm-inputhub_e2edc.sh /    
# ------------------------------------------------
RUN gem update
# ------------------------------------------------
COPY ./install/gems/dec_s2.gem .
RUN gem install dec_s2.gem
# ------------------------------------------------
# ------------------------------------------------
# Patch log4r
COPY ./install/patch/rollingfileoutputter.rb /usr/local/bundle/gems/log4r-1.1.10/lib/log4r/outputter/
# ------------------------------------------------
# MKDIR p /volumes/dec
RUN mkdir -p /volumes/dec/log && \
    chown -R 10001:10001 /volumes/dec
## ------------------------------------------------
#RUN service postgresql start
## ------------------------------------------------
#USER postgres
#RUN    /etc/init.d/postgresql start &&\
#    psql --command "CREATE USER e2edc WITH SUPERUSER PASSWORD 'e2edc';" &&\
#    createdb -O e2edc e2edc
USER e2edc
RUN   mkdir -p /home/e2edc/.ssh
COPY ./config/ssh/* /home/e2edc/.ssh/
COPY ./config/ssh/e2espm.e2espm-esrin.private /home/e2edc/.ssh/id_rsa
COPY ./config/ssh/known_hosts_pdmcdag1.sentinel2.eo.esa.int /home/e2edc/.ssh/known_hosts
ENV   HOSTNAME=dec GEM_HOME=/usr/local/bundle PATH="/usr/local/bundle/bin:${PATH}"
# "------------------------------------------------
# Initialise DEC
RUN decManageDB -c
RUN decConfigInterface2DB -p EXTERNAL
# ------------------------------------------------
ENTRYPOINT ["/usr/bin/entrypoint_dec_s2_e2espm-inputhub_e2edc.sh"]
