#########################################################################
###
### Git:
###     Dockerfile.minarc.s2.inputhub  
###                          $Author: bolf$
###                          $Date: 2018-11-13T11:54:43+01:00$ 
###                          $Committer: bolf$
###                          $Hash: f3afa7c$
###
#########################################################################
#
# Dockerfile for minARC S2 INPUTHUB
# 
# (Debian 10 Buster)
#
FROM ruby:2.6
# ================================================
# coreutils expected to bring md5sum
RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y --no-install-recommends \
    jq \
    net-tools \
    ftp \
    libxml2 \
    libxml2-utils \
    coreutils \
    xml-twig-tools \
    p7zip-full \
    sqlite3 \
    libsqlite3-dev \
    ncftp \
    curl \
    vim
# ------------------------------------------------
RUN apt-get install -y postgresql-client
# ------------------------------------------------
# ------------------------------------------------
RUN groupadd -g 10001 dec && \
    useradd -u 10001 -ms /bin/bash -g dec -d /home/dec dec
# ------------------------------------------------
COPY ./install/scripts/entrypoint_s2decservice_minarc.sh /usr/bin/
RUN ln -s /usr/bin/entrypoint_s2decservice_minarc.sh /    
# ------------------------------------------------
RUN gem update
# ------------------------------------------------
COPY ./install/gems/minarc_s2_pg.gem .
RUN gem install minarc_s2_pg.gem
# ------------------------------------------------
# ------------------------------------------------
# Patch log4r
COPY ./install/patch/rollingfileoutputter.rb /usr/local/bundle/gems/log4r-1.1.10/lib/log4r/outputter/
# ------------------------------------------------
# 
#RUN mkdir -p /volumes/dec/minarc/log && \
#    chown -R 10001:10001 /volumes/dec
# ------------------------------------------------
USER dec
ENV   HOSTNAME=minarc GEM_HOME=/usr/local/bundle PATH="/usr/local/bundle/bin:${PATH}"
# "------------------------------------------------
ENTRYPOINT ["/usr/bin/entrypoint_s2decservice_minarc.sh"]
