#!/usr/bin/ruby

#########################################################################
##
## Ruby source for #CryptHelper class
##
## Written by DEIMOS Space S.L.
##
## Data Exchange Component -> Common Utils Component
## 
## git: $Id: CryptHelper.rb,v Exp $
##
#########################################################################

require 'openssl'
require 'base64'
require 'open3'

require 'cuc/Log4rLoggerFactory'

# https://wiki.openssl.org/index.php/Main_Page

# Module Common Utils Component
# This module provides helpers to encrypt / decrypt strings

module CUC

module CryptHelper

   ## -------------------------------------------------------------

   # echo -n "hola" | openssl enc -e -base64 -rc4 -nosalt -pass pass:secretkey -p
   # echo -n "oSW1ww==" | openssl enc -d -base64 -rc4 -nosalt -pass pass:secretkey -p

   def cmdEncrypt(plaintext, password, bIsDebug = false)
      cmd = "echo \"#{plaintext}\" | openssl enc -e -base64 -rc4 -nosalt -pass pass:#{password}"

      if bIsDebug == true then
         puts cmd
      end

      str, status = Open3.capture2e(cmd)
      return str.chop
   end
   ## -------------------------------------------------------------

   # echo -n "hola" | openssl enc -d -base64 -rc4 -nosalt -pass pass:secretkey

   def cmdDecrypt(plaintext, password, bIsDebug = false)
      cmd = "echo \"#{plaintext}\" | openssl enc -d -base64 -rc4 -nosalt -pass pass:#{password}"
      if bIsDebug == true then
         puts cmd
      end
      str = `#{cmd}`
      return str.chop
   end
   ## -------------------------------------------------------------   
   ## echo -n "hola" | openssl enc -e -base64 -rc4 -nosalt -pass pass:secretkey -p
   ##
   def encrypt(plaintext, key)
      cipher = OpenSSL::Cipher.new('rc4')
      cipher.encrypt
      # Use the key that was generated by EVP_BytesToKey
      # key = '610A2EE688CDA9E724885E23CD2CFDEE'
      # Convert the key to a byte string
      key_bytes   = key.scan(/../).map { |x| x.hex.chr }.join
      cipher.key  = key_bytes
      ciphertext  = cipher.update(plaintext) + cipher.final
      base64 = Base64.strict_encode64(ciphertext)
   end
   ## -------------------------------------------------------------

   ## echo "ryW2" | openssl enc -d -base64 -rc4 -nosalt -pass pass:secretkey
   ## 
   def decrypt(encrypted64, key)
      encryptedtext  = Base64.decode64(encrypted64)
      decipher       = OpenSSL::Cipher.new('rc4')
      decipher.decrypt
      key_bytes      = key.scan(/../).map { |x| x.hex.chr }.join
      decipher.key   = key_bytes
      decrypted      = decipher.update(encryptedtext) + decipher.final
   end
   ## -------------------------------------------------------------

   def encrypt_md5(plaintext, key)
      cipher = OpenSSL::Cipher.new('RC4')
      cipher.key = OpenSSL::Digest.digest('md5', key)
      cipher.decrypt
      Base64.encode64(cipher.update(plaintext) + cipher.final)
   end
   ## -----------------------------------------------------------
   ##
   ## 
   def decrypt_md5(encryptedtext, key)
      decipher = OpenSSL::Cipher.new('RC4')
      decipher.key = OpenSSL::Digest.digest('md5', key)
      decipher.decrypt
      decipher.update(Base64.decode64(encryptedtext)) + decipher.final
   end
   ## -------------------------------------------------------------

   def getChi(strProject)
      if strProject.downcase == 'dec' then
         return '000000000000000000000000$DEC2020'
         #return Base64.encode64('000000000000000000000000$DEC2020')
      end

      raise "encryption reference not found or supported"
   end
   ## -----------------------------------------------------------
   
   def getMagikGuord(strProject)
      if strProject.downcase == 'dec' then
         return '$DEC2020$'
      end

      raise "encryption reference not found or supported"
   end
   ## -----------------------------------------------------------

end # module

end # module
