#!/usr/bin/env ruby

# == Synopsis
#
# This is a Data Exxchange Component command line tool that manages the I/Fs listeners for data retrieval
#
# == Usage
# decListener  --all [-R]| --mnemonic <MNEMONIC> --interval <seconds>
#     --all                 starts a listener for each I/Fs
#     --Reload              force a Restart of all listeners
#     --stop <MNEMONIC>     it stops of the listener for the given I/F
#     --Stop                it stops of all listeners
#     --check               it checks whether the listeners are running
#     --mnemonic <MNEMONIC> (mnemonic is case sensitive)
#     --interval            the frequency it is polled I/F given by MNEMONIC (in seconds)
#     --nodb                no Inventory recording
#     --no-intray           skip step of delivery to intrays upon download
#     --help                shows this help
#     --Debug               shows Debug info during the execution
#     --version             shows version number      
# 
# == Author
# DEIMOS-Space S.L. (bolf)
#
# == Copyright
# Copyright (c) 2005 ESA - DEIMOS Space S.L.
#


#########################################################################
#
# === Data Exchange Component -> Data Collector Component
#
# CVS: $Id: decListener,v 1.8 2008/07/03 11:38:07 decdev Exp $
#
#########################################################################



 # DCC Daemon process which listens to incoming files and dispatches them
 # into the proper directories, depending on the configuration file
 # ft_incoming_files.xml.
 # It agregates #DCC_Listener to implement a daemon.


require 'rubygems'
require 'getoptlong'

require 'cuc/Listener'
require 'cuc/Log4rLoggerFactory'
require 'cuc/DirUtils'
require 'cuc/CheckerProcessUniqueness'
require 'cuc/CommandLauncher'
require 'ctc/ReadInterfaceConfig'
require 'dcc/ReadConfigDCC'
require 'dec/DEC_Environment'

# Global variables
@dateLastModification = "$Date: 2008/07/03 11:38:07 $"   


# MAIN script function
def main

   include DEC
   include CUC::DirUtils
   include CUC::CommandLauncher

   @isDebugMode        = false
   @launchAllListeners = false
   @bCheckListeners    = false
   @bStopListeners     = false
   @isReload           = false
   @isNoDB             = false
   @isNoIntray         = false
   @bShowVersion       = false
   @bShowUsage         = false
   @mnemonic           = "" 
   @intervalSeconds    = 0
     
   opts = GetoptLong.new(
      ["--mnemonic", "-m",       GetoptLong::REQUIRED_ARGUMENT],     
      ["--interval", "-i",       GetoptLong::REQUIRED_ARGUMENT],
      ["--stop", "-s",           GetoptLong::REQUIRED_ARGUMENT],
      ["--usage", "-u",          GetoptLong::NO_ARGUMENT],
      ["--Debug", "-D",          GetoptLong::NO_ARGUMENT],
      ["--all", "-a",            GetoptLong::NO_ARGUMENT],
      ["--Stop", "-S",           GetoptLong::NO_ARGUMENT],
      ["--check", "-c",          GetoptLong::NO_ARGUMENT],
      ["--Reload", "-R",         GetoptLong::NO_ARGUMENT],
      ["--version", "-v",        GetoptLong::NO_ARGUMENT],
      ["--help", "-h",           GetoptLong::NO_ARGUMENT],
      ["--no-intray", "-N",      GetoptLong::NO_ARGUMENT],
      ["--nodb", "-n",           GetoptLong::NO_ARGUMENT]
      )

   begin
      opts.each do |opt, arg|
         case opt
            when "--all"      then @launchAllListeners   = true
	         when "--check"    then @bCheckListeners      = true
            when "--Debug"    then @isDebugMode          = true
            when "--Reload"   then @isReload             = true
            when "--version"  then @bShowVersion         = true            
            when "--mnemonic" then @mnemonic             = arg            
            when "--help"     then @bShowUsage           = true
            when "--interval" then
               @intervalSeconds = arg.to_i
	         when "--stop"     then
               if existEntity?(arg.to_s) == false then
                  puts
                  puts "#{arg.to_s} is not a registered I/F"
                  puts
                  exit(99)
               end
               stopListener(arg.to_s)
               stopGetFromEntity(arg.to_s)
               exit(0)
            when "--Stop"           then @bStopListeners    = true
            when "--usage"          then @bShowUsage        = true
            when "--nodb"           then @isNoDB            = true
            when "--no-intray"      then @isNoIntray        = true
         end
      end
   rescue Exception
      exit(99)
   end 
   
   if @bShowVersion == true then
      print("\nESA - DEIMOS-Space S.L. ", File.basename($0), " Version: [#{DEC.class_variable_get(:@@version)}]", "\n\n\n")
      exit(0)
   end   

   if @bShowUsage == true then
      usage
      exit(0)
   end

   # initialize logger
   loggerFactory = CUC::Log4rLoggerFactory.new("decListener", "#{ENV['DEC_CONFIG']}/dec_log_config.xml")
   if @isDebugMode then
      loggerFactory.setDebugMode
   end
   @logger = loggerFactory.getLogger
   if @logger == nil then
      puts
		puts "Error in decListener::main"
		puts "Could not set up logging system !  :-("
      puts "Check DEC logs configuration under \"#{ENV['DEC_CONFIG']}/dec_log_config.xml\"" 
		puts
		puts
		exit(99)
   end
   
   if @bCheckListeners == true then
      checkListeners
      exit(0)
   end

   if @bStopListeners == true then
   	stopListeners
	   puts "\nlisteners to the I/Fs have been killed ! }=-) \n\n"
      exit(0)
   end

   if @isReload == true and @launchAllListeners == false then
      usage
   end
 
   if @launchAllListeners == false and (@mnemonic == "" or @intervalSeconds == 0) then
      usage
   end
 
   # CheckModuleIntegrity
   checkModuleIntegrity
 
   @projectName = DCC::ReadConfigDCC.instance.getProjectName
   @projectID   = DCC::ReadConfigDCC.instance.getProjectID

   if @launchAllListeners == true then
      if @isReload == false then
         launchListeners
      else
         restartListeners
      end
      exit(0)
   else
      
      if existEntity?(@mnemonic) == false then
         puts
         puts "Could not start a listener for #{@mnemonic} I/F !  :-("
         puts
         puts "#{@mnemonic} is not a registered I/F"
         puts
         exit(99)
      end
   
      # Register a listener for this I/F.
      # Create our lovely listener and start it.
      listener = CUC::Listener.new(File.basename($0), @mnemonic, @intervalSeconds,
                              self.method("pollInterface").to_proc)

      trap("SIGHUP") {  
                        puts "\nPolling requested for #{@mnemonic} I/F ...\n"
                        @logger.info("Polling Requested for #{@mnemonic} I/F")
                     }   

      if @isDebugMode == true
         listener.setDebugMode
      end
		   
      # start server
      listener.run
   end
end
#-------------------------------------------------------------

# By requirements it is needed one listener per I/F with an
# independent PollingInterval for each one.
def pollInterface
   startTime = Time.new
   startTime.utc   
   puts "Polling #{@mnemonic} I/F ..."
   # @logger.info("Polling #{@mnemonic} I/F ...")
   @logger.debug("Polling #{@mnemonic} I/F ...")
      
   if @isDebugMode == true then
      command  = %Q{decGetFromInterface --mnemonic #{@mnemonic} -D}
   else
      command  = %Q{decGetFromInterface --mnemonic #{@mnemonic}}
   end
   
   # ----------------------------------------------------------
   # 20160907
   # decGetFromInterface --del-unknown flag would need a cleaner approach
   # New attribute in configuration file is needed

#   command  = %Q{#{command} --del-unknown} 

   # ----------------------------------------------------------
   
   if @isNoDB == true then
      command  = %Q{#{command} --nodb}
   end

   if @isNoIntray == true then
      command  = %Q{#{command} --no-intray}
   end


   # ----------------------------------------------------------

   if @isDebugMode == true then
      puts "#{command}"
   end

   # puts command

# DCC Commands provide a lot of console output
# Because of this, if it is desired to use DCC_CommandLauncher execute
# They must implement a kind of silent mode.   
#   retVal = execute(command, "decListener")
   retVal = system(command)
      
   if retVal == true then
      puts "Success Polling #{@mnemonic} I/F !\n\n"
      # @logger.info("Success Polling #{@mnemonic} I/F !")
      @logger.debug("Success Polling #{@mnemonic} I/F !")
   else
      puts "ERROR Polling #{@mnemonic} I/F !\n\n"
      @logger.error("Could not Poll #{@mnemonic} I/F !")
      # if previous polling failed, retry again inmediately
      
      # -------------------------------------
      # 20170518 
      
      # With multiple simultaneous downloads on the same server,
      # error condition can now be different a network glitch 
      # but connectivity rejection by FW in between which can associate
      # this scenario with a DoS attack, 
      # hence inmediate retry brings inmediate rejection by FW
      #  
      # This waiting time to remove DCC from FW temporal blacklist
      # should become an adaptative one, for the time being set 
      # to two minutes with S2PDGS PDMC observations
      
      sleep(120)
      
      # -------------------------------------
      
      return 1
   end 

   # calculate required time and new interval time.
   stopTime     = Time.new
   stopTime.utc   
   requiredTime = stopTime - startTime
   
   nwIntSeconds = @intervalSeconds - requiredTime.to_i
   
   if @isDebugMode == true and nwIntSeconds > 0 then
      puts "New Trigger Interval is #{nwIntSeconds} seconds | #{@intervalSeconds} - #{requiredTime.to_i}"
   end
   
   if @isDebugMode == true and nwIntSeconds < 0 then
      puts "Time performed for polling is higher than interval Server !"
      puts "polling interval -> #{@intervalSeconds} seconds "
      puts "time required    -> #{requiredTime.to_i} seconds "
      puts
   end
      
   # The lowest time we return is one second. 
   # 0 would produce the process to sleep forever.
    
   if nwIntSeconds > 0 then
      return nwIntSeconds
   else
      return 1
   end
   
end
#-------------------------------------------------------------

# By requirements it is needed one listener per I/F with an
# independent PollingInterval for each one.
#
# It is required to provide a method to trigger and restart
# all I/Fs Listeners on demand.
def restartListeners
   
   ftReadConf   = CTC::ReadInterfaceConfig.instance
   arrEntities  = ftReadConf.getAllExternalMnemonics
   arrPIDs      = Array.new
   
   arrEntities.each{|x|
       if ftReadConf.isEnabled4Receiving?(x) == true then
	       checker = CUC::CheckerProcessUniqueness.new(File.basename($0), x, true)
         if checker.getRunningPID == false then
            puts "\nThere was not a listener for #{x} I/F running !\n"
            launchListener(x)
         else
            pid = checker.getRunningPID
            puts "Sending signal 1 to Process #{pid} for restarting #{x} I/F"
            Process.kill(1, pid.to_i)
         end     
       end
   }   
   
end
#-------------------------------------------------------------

# It Stops all the Listeners
def stopListeners
   ftReadConf   = CTC::ReadInterfaceConfig.instance
   arrEntities  = ftReadConf.getAllExternalMnemonics
   arrPIDs      = Array.new
   @logger.info("Stopping all I/Fs ...")
   arrEntities.each{|x|
      if ftReadConf.isEnabled4Receiving?(x) == true then
         stopListener(x)
      end
   }   
   stopGetFromEntities
end
#-------------------------------------------------------------

# It stops the listener for the given I/F
def stopListener(mnemonic)
   checker = CUC::CheckerProcessUniqueness.new(File.basename($0), mnemonic, true)
   pid     = checker.getRunningPID
   if pid == false then
      puts "There was not a listener for #{mnemonic} I/F running !"
      @logger.info("Listener for #{mnemonic} I/F was not running")
   else
      puts "Sending signal SIGKILL to Process #{pid} for killing #{mnemonic} I/F"
      Process.kill(9, pid.to_i)
	   checker.release
      @logger.info("Listener for #{mnemonic} I/F has been disabled")
   end
end
#-------------------------------------------------------------

# It checks whether the Listeners are running or not
# It returns:
# * 0 -> All listeners are running
# * 1 -> All listeners are not running
# * 2 -> Some of them are not running
#
def checkListeners
   ftReadConf   = CTC::ReadInterfaceConfig.instance
   arrEntities  = ftReadConf.getAllExternalMnemonics
   bAll  = true
   bNone = true
   arrEntities.each{|x|
       checker = CUC::CheckerProcessUniqueness.new(File.basename($0), x, true)
       if @isDebugMode == true then
          checker.setDebugMode
       end
       ret     = checker.isRunning
       if ret == false then
          if ftReadConf.isEnabled4Receiving?(x) == true then
             puts "There is not a listener for #{x} I/F running !"
             bAll = false
          end  
       else
          puts "listener for #{x} I/F is running"
          bNone = false
       end
   }
   puts
   if bAll == true then
      exit(0)
   end
   if bNone == true then
      exit(1)
   end
   exit(2)
end
#-------------------------------------------------------------

# By requirements it is needed one listener per I/F with an
# independent PollingInterval for each one.
def launchListeners      
   ftReadConf   = CTC::ReadInterfaceConfig.instance
   arrEntities  = ftReadConf.getAllExternalMnemonics
   
   puts "Polling #{@projectName} Interfaces ..."
	puts
   
   @logger.info("Starting all Listeners ...")
   
   startTime = Time.new
   startTime.utc
        
   # Create a process for sending the Files to each entity
	arrEntities.each{|entity|
      if ftReadConf.isEnabled4Receiving?(entity) == true then
	      launchListener(entity)
      end
	}
   puts
   return 0   
end
#-------------------------------------------------------------

# It creates a new process Listener for the I/F.
def launchListener(entity)
   ftReadConf   = CTC::ReadInterfaceConfig.instance      
   pI = ftReadConf.getPollingInterval(entity)
   if @isDebugMode == true then
      command  = %Q{decListener --mnemonic #{entity} --interval #{pI} -D}
   else
      command  = %Q{decListener --mnemonic #{entity} --interval #{pI}}
   end
   puts command
   @logger.info("Starting Listener for #{entity} I/F")
   #---------------------------------------------
   # Create a new process for each Entity
   pid = fork {
      Process.setpriority(Process::PRIO_PROCESS, 0, 1)
      if @isDebugMode == true then
         puts command
      end
      retVal = execute(command, "decListener")
      if retVal == true then
			exit(0)
      else
         # @logger.error("Could not launch listener for #{entity} I/F")
		   puts "Error launching listener for #{entity}"
         exit(99)
      end            
   }
   #---------------------------------------------
end
#-------------------------------------------------------------

# It stops getFromInterface associated to each listener
def stopGetFromEntities
   ftReadConf   = CTC::ReadInterfaceConfig.instance
   arrEntities  = ftReadConf.getAllExternalMnemonics
   arrPIDs      = Array.new
   puts
#   @logger.info("Abort current polling Operations ...")
   
   arrEntities.each{|x|
      if ftReadConf.isEnabled4Receiving?(x) == true then
         stopGetFromEntity(x)
      end
   } 
end
#-------------------------------------------------------------

# It stops getFromInterface for a given I/F
def stopGetFromEntity(mnemonic)
   checker = CUC::CheckerProcessUniqueness.new("decGetFromInterface", mnemonic, true)
   pid     = checker.getRunningPID
   if pid == false then
      puts "There was not a decGetFromInterface for #{mnemonic} I/F running !"
   else
      puts "Sending signal SIGKILL to Process #{pid} for killing decGetFromInterface -m #{mnemonic}"
      @logger.info("Abort current polling Operations ...")
      Process.kill(9, pid.to_i)
	   checker.release
      @logger.info("Polling for #{mnemonic} I/F has been aborted")
   end
end
#-------------------------------------------------------------

# It exists?
def existEntity?(mnemonic)
   ftReadConf   = CTC::ReadInterfaceConfig.instance   
   return ftReadConf.exists?(mnemonic)
end
#-------------------------------------------------------------

# Check that everything needed by the class is present.
def checkModuleIntegrity
   
   bDefined = checkEnvironmentEssential

   if bDefined == false then
      puts "\nError in decListener::checkModuleIntegrity :-(\n\n"
      exit(99)
   end                             
end
#-------------------------------------------------------------

#-------------------------------------------------------------

# Print command line help
def usage
   fullpathFile = File.expand_path(__FILE__)   
   
   value = `#{"head -27 #{fullpathFile}"}`
      
   value.lines.drop(1).each{
      |line|
      len = line.length - 1
      puts line[2, len]
   }
end
#-------------------------------------------------------------



#===============================================================================
# Start of the main body
main
# End of the main body
#===============================================================================
