#!/usr/bin/env ruby -W0

#########################################################################
##
## === Ruby source for #DEC_TestCases class
##
## === Written by DEIMOS Space S.L. (bolf)
##
## === Data Exchange Component
## 
## module DEC
##
#########################################################################

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'cuc/Log4rLoggerFactory'

require 'ctc/FTPClientCommands'
require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'
require 'dec/ReadInterfaceConfig'
require 'dec/ReadConfigOutgoing'
require 'dec/ReadConfigIncoming'


# rake -f build_dec.rake dec:install[gsc4eo,nl2-u-moc-srv-01,naos_test]

class DECTestCaseCelesTrak < Test::Unit::TestCase

   include CUC::DirUtils
   include CTC::FTPClientCommands
   include DEC

   
   # Order of the test cases execution according to defintion within code
   self.test_order = :defined
   
   @my_argv = ARGV.dup
   
   ## ------------------------------------------------------
   
   Test::Unit.at_start do      
      puts
      puts "======================================"
      puts "DEC Interface Test Cases for CelesTrak"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   
      
      @@conf = DEC_Environment.new
      
      @@conf.wrapper_load_config
                             
      @@conf.wrapper_print_environment
                           
      @@conf.createEnvironmentDirs
                                    
      if @@conf.wrapper_check_environment == false then
         puts "DEC environment not suited for unit tests"
         puts
         exit(99)
      end
                     
                     
      # initialize logger
                           
      loggerFactory = CUC::Log4rLoggerFactory.new("test", "#{ENV['DEC_CONFIG']}/dec_log_config.xml")
                           
      if @isDebugMode then
         loggerFactory.setDebugMode
      end
      
      @@logger = loggerFactory.getLogger
                           
      if @@logger == nil then
         puts
         puts "Error in decUnitTests::main"
         puts "Could not set up logging system !  :-("
         puts "Check DEC logs configuration under \"#{ENV['DEC_CONFIG']}/dec_log_config.xml\"" 
         puts
         puts
         exit(99)
      end
      
      
   end
   
   ## ------------------------------------------------------
   
   Test::Unit.at_exit do
      @@logger.info("End of DEC test for Celestrak")
   end
   
   ## ------------------------------------------------------
   
   ## Setup before every test-case
   ##
   def setup
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
                  
      decConfig   = DEC::ReadConfigDEC.instance
      reportDir   = decConfig.getReportDir

      system("\\rm -rf #{reportDir}")
      # system("\\rm -rf /tmp/dec*")
      system("\\rm -rf /tmp/DEC*.log")
      system("\\rm -rf /data/mocExternalInterfaces/log/DEC*.log")
      system("\\rm -rf /data/mocExternalInterfaces/tmp/mocIN/tmp/*")
      system("\\rm -rf /data/mocExternalInterfaces/tmp/mocIN/*")
      system("\\rm -rf /data/mocExternalInterfaces/tmp/mocOUT/*")
      system("\\rm -rf /data/mocExternalInterfaces/tmp/mocOUT/tmp/*")
      system("\\rm -rf /data/mocExternalInterfaces/FDS/inTray/CEL/AUX_TLE/NS1*")
      system("\\rm -rf /data/mocExternalInterfaces/FDS/inTray/CEL/AUX_TCA/NS1*")
      system("\\rm -rf /data/mocExternalInterfaces/KSA/inTray/CEL/AUX_TLE/NAOS1*")
      system("\\rm -rf /data/mocExternalInterfaces/DDC/inTray/CEL/AUX_TLE/NAOS1*")
      system("\\rm -rf /data/mocExternalInterfaces/delivery_root/NS1*")
      system("\\rm -rf /data/mocExternalInterfaces/delivery_root/NAOS1*")
      system("\\rm -rf /data/mocExternalInterfaces/outbox/ddc/sftp/*")
      system("\\rm -rf /data/mocExternalInterfaces/outbox/aut/sftp/*")
      system("\\rm -rf /data/mocExternalInterfaces/outbox/ksa/sftp/*")
      system("mkdir -p /data/mocExternalInterfaces/tmp/mocIN/tmp/")
      system("mkdir -p /data/mocExternalInterfaces/tmp/mocOUT/tmp/")

      cmd = "decManageDB -d"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decManageDB -c"
      @@logger.debug(cmd)
      ret = system(cmd)
      
      cmd = "decValidateConfig -a"
      @@logger.debug(cmd)
      ret = system(cmd)
      
      cmd = "decConfigInterface2DB -p EXTERNAL"
      @@logger.debug(cmd)
      ret = system(cmd)   
            
   end
   ## --------------------------------------------------------
   ## After every test case

   def teardown
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
   end
   ## ------------------------------------------------------

   ## -----------------------------------------------------------
   def testSFS
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START")

      cmd = "decConfigInterface2DB -a TEST_CELESTRAK_SFS"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decCheckConfig -e TEST_CELESTRAK_SFS"
      @@logger.info(cmd)
      assert(system(cmd), "list from TEST_CELESTRAK_SFS")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_SFS -l"
      @@logger.info(cmd)
      assert(system(cmd), "list from TEST_CELESTRAK_SFS")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_SFS --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_SFS")
     
      # New iteration should not drive to a new file
      # A duplication should be detected.
      cmd = "decGetFromInterface -m TEST_CELESTRAK_SFS --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_SFS")

      cmd = "decStats"
      @@logger.info(cmd)
      assert(system(cmd), "pull statistics")
   
      arr = Dir["/tmp/DEC*.log"]
      arr = Dir["/data/mocExternalInterfaces/log/DEC*.log"]

      @@logger.debug("Verification of log trace: SFS conversion to NAOS mission")
      cmd = "grep AUX\_001 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "SFS conversion to NAOS mission traced in DEC logs in #{__method__.to_s}") 

      @@logger.debug("Verification of log trace: Duplication of short-term weather forecast")
      cmd = "grep DEC\_111 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "SFS duplication traced in DEC logs in #{__method__.to_s}") 

      cmd = "grep ERROR #{arr[0]}"
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 
   
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END")
   end
   ## -----------------------------------------------------------

   ## -----------------------------------------------------------

   def testTLE
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START")

      cmd = "decCheckConfig -e TEST_CELESTRAK_TLE"
      @@logger.info(cmd)
      assert(system(cmd), "list from TEST_CELESTRAK_TLE")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TLE -l"
      @@logger.info(cmd)
      assert(system(cmd), "list from TEST_CELESTRAK_TLE")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TLE --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_TLE")
     
      # New iteration should not drive to a new file
      # A duplication should be detected.
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TLE --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_TLE")

      cmd = "decStats"
      @@logger.info(cmd)
      assert(system(cmd), "pull statistics")
   
      arr = Dir["/tmp/DEC*.log"]
      arr = Dir["/data/mocExternalInterfaces/log/DEC*.log"]

      @@logger.debug("Verification of log trace: TLE conversion to NAOS mission")
      cmd = "grep AUX\_001 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "TLE conversion to NAOS mission traced in DEC logs in #{__method__.to_s}") 

      @@logger.debug("Verification of log trace: Duplication of TLE")
      cmd = "grep DEC\_111 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "TLE duplication traced in DEC logs in #{__method__.to_s}") 

      cmd = "grep ERROR #{arr[0]}"
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 
   
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END")
   end   

   ## ------------------------------------------------------

   ## -----------------------------------------------------------

     def testTCA
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START")

      cmd = "rm -f /tmp/dec/int/NS1_OPER_AUX_TCA____*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/dec/in_basket_if_celes/tca/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "decConfigInterface2DB -a TEST_CELESTRAK_TCA"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decCheckConfig -e TEST_CELESTRAK_TCA"
      @@logger.info(cmd)
      assert(system(cmd), "list from TEST_CELESTRAK_TCA")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TCA -l"
      @@logger.info(cmd)
      assert(system(cmd), "list from CELESTRAK_TCA")
   
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TCA --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_TCA")
     
      # New iteration should not drive to a new file
      # A duplication should be detected.
      cmd = "decGetFromInterface -m TEST_CELESTRAK_TCA --no-intray"
      @@logger.info(cmd)
      assert(system(cmd), "pull from TEST_CELESTRAK_TCA")

      cmd = "decStats"
      @@logger.info(cmd)
      assert(system(cmd), "pull statistics")
   
      arr = Dir["/tmp/DEC*.log"]
      arr = Dir["/data/mocExternalInterfaces/log/DEC*.log"]

      @@logger.debug("Verification of log trace: TCA conversion to NAOS mission")
      cmd = "grep AUX\_001 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "TCA conversion to NAOS mission traced in DEC logs in #{__method__.to_s}") 

      @@logger.debug("Verification of log trace: Duplication of TCA")
      cmd = "grep DEC\_111 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "TCA duplication traced in DEC logs in #{__method__.to_s}") 

      cmd = "grep ERROR #{arr[0]}"
      #@@logger.debug(cmd)
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 
   
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END")
   end   

   ## ------------------------------------------------------


end


## ===================================================================




