#!/usr/bin/env ruby

#########################################################################
###
### === Ruby source for #decUnitTests_FTP class
###
### === Written by DEIMOS Space S.L.
###
### === Data Exchange Component
###
### # git: decUnitTests_FTP,v $Id$: 
### 
### module DEC
###
#########################################################################

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'cuc/Log4rLoggerFactory'

require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'

## rake -f build_dec.rake dec:install[borja,localhost,s2_test_pg]

### ------------------------------------
### MacOS Catalina
## cd $HOME (non root $PWD)
## sudo /usr/local/sbin/pure-ftpd
## PAMAuthentication            yes

### ------------------------------------
### MacOS Mojave
## sudo /usr/local/sbin/pure-ftpd -lpam
## sudo /usr/local/sbin/pure-ftpd /Users/borja/Projects/dec/config/ftp/pure-ftpd.conf
### ------------------------------------

## https://bobcares.com/blog/proftpd-create-user/

## https://support.hostway.com/hc/en-us/articles/360000563730-How-to-enable-passive-FTP-connections-in-ProFTPD

class DECTestCase_FTP < Test::Unit::TestCase

   include Test::Unit::Data
   
   include CUC::DirUtils
   
   include DEC
         
   # Order of the test cases execution according to definition within code
   self.test_order = :defined
   
   @my_argv = ARGV.dup
   # --------------------------------------------------------
   
   Test::Unit.at_start do
      system("clear")
      puts
      puts "======================================"
      puts "DEC FTP Unit Test Cases"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   
   
   
      @@arrDownloadFiles = [ \
                           "finals.all", \
                           "tai-utc.dat" \
                           ]

      @@conf = DEC_Environment.new

      @@conf.wrapper_load_config

      @decConfigDir = ENV['DEC_CONFIG']
 
      ## ----------------------------------
      ## initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("DECTEST", "#{@decConfigDir}/dec_log_config.xml")
   
      @@logger = loggerFactory.getLogger   
      if @@logger == nil then
         puts
		   puts "Error in decUnitTests_FTP"
     	   puts "Could not initialize logging system !  :-("
         puts "Check DEC logs configuration under \"#{@decConfigDir}/orchestrator_log_config.xml\"" 
 	      puts
   	   exit(99)
      end

      ## ----------------------------------
      @@conf.wrapper_unset_config
   
   end
   
   ## --------------------------------------------------------
   
   Test::Unit.at_exit do
      puts "End of DEC tests FTP"
   end
   ## --------------------------------------------------------   
   
   # Setup before every test-case
   #
   def setup
      cmd = "mkdir -p /tmp/tmp/dir1"
      puts cmd
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dir2"
      puts cmd
      system(cmd)
      
      return
   end
   ## ------------------------------------------------------
   ## After every test case

   def teardown
      return
   end
   ## ------------------------------------------------------
   
   ## ------------------------------------------------------
   
   ##
   
   ## PULL Circulations
   def test_pull
      @@logger.debug("#{File.basename(__FILE__)}::#{__method__.to_s}")
      checkDirectory("/tmp/dec/in_basket_if_localhost_ftp")
      
      system("\\rm -rf /tmp/dec/in_basket_if_localhost_ftp/*")

      cmd = "rm -f /tmp/DEC*.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "decManageDB -d"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decManageDB -c"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decConfigInterface2DB -p EXTERNAL"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decValidateConfig -a"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)   
   
      cmd = "decCheckConfig -e LOCALHOST_FTP"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      ## -----------------------------------------
      ## list mode and subsequent download
      
      system("echo \'my touch file\' > /tmp/tmp/dir1/touchfile1.txt")
      system("echo \'another touch file\' > /tmp/tmp/dir1/touchfile2.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile3.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile4.txt")
            
      cmd = "decGetFromInterface -m LOCALHOST_FTP -l -D"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      cmd = "decGetFromInterface -m LOCALHOST_FTP -D"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      arrFiles = Dir["/tmp/dec/in_basket_if_localhost_ftp/touch*"]      
      assert(arrFiles.length == 4, "Number of files pulled")
      
      ## -----------------------------------------

      
      ## -----------------------------------------
      ## Download again since --nodb is used to avoid filtering by previous download
          
      system("\\rm -rf /tmp/dec/in_basket_if_localhost_ftp/*")
      
      system("echo \'my touch file\' > /tmp/tmp/dir1/touchfile1.txt")
      system("echo \'another touch file\' > /tmp/tmp/dir1/touchfile2.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile3.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile4.txt")
            
      cmd = "decGetFromInterface -m LOCALHOST_FTP --nodb"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
 
      arrFiles = Dir["/tmp/dec/in_basket_if_localhost_ftp/touch*"]      
      assert(arrFiles.length == 4, "Number of files pulled")

      ## -----------------------------------------
      ## Now no files should be present for download

      system("\\rm -rf /tmp/dec/in_basket_if_localhost_ftp/*")
      
      cmd = "decGetFromInterface -m LOCALHOST_FTP"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
            
      arrFiles = Dir["/tmp/dec/in_basket_if_localhost_ftp/touch*"]      
      assert(arrFiles.length == 0, "Number of files pulled")

      ## -----------------------------------------

      cmd = "decStats -H 1"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      
      ## -----------------------------------------
      
      arr = Dir["/tmp/DEC*.log"]

      system("\\rm -rf /tmp/dec/in_basket_if_localhost_ftp/*")
      
      system("echo \'my touch file\' > /tmp/tmp/dir1/touchfile1.txt")
      system("echo \'another touch file\' > /tmp/tmp/dir1/touchfile2.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile3.txt")
      system("echo \'another brick in the touch file\' > /tmp/tmp/dir2/touchfile4.txt")
            
      cmd = "decGetFromInterface -m LOCALHOST_FTP"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
 
      arrFiles = Dir["/tmp/dec/in_basket_if_localhost_ftp/touch*"]      
      assert(arrFiles.length == 0, "Duplicated files should not be pulled")
                      
      cmd = "grep DEC_125 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "Duplications logged in #{__method__.to_s}") 

      ## -----------------------------------------
      
   end
   ## ------------------------------------------------------

   ## ------------------------------------------------------
   
   # data("SEPARATOR",     ["TEST LABEL",     0,   0,   0,    false])
   data("0",     ["1_files_10GB_1Slots_NoDB",      1,   1024000,   1,     true])
   data("1",     ["3_files_10GB_1Slots_NoDB",      3,   1024000,   1,     true])
   data("2",     ["7_files_10GB_1Slots_NoDB",      7,   1024000,   1,     true])

   ## PUSH Circulations
   def test_push(params)

      label, numFiles, numBlocks, numSlots, noDB = params

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START #{label}")

      cmd = "rm -f /tmp/DEC*.log"
      @@logger.debug(cmd)
      system(cmd)

      checkDirectory("/tmp/dec_simul_if/localhost_notsecure/upload")
      system("\\rm -rf /tmp/dec_simul_if/localhost_notsecure/upload/*")

      checkDirectory("/tmp/dec_simul_if/localhost_notsecure/upload/_TEMP_")
      system("\\rm -rf /tmp/dec_simul_if/localhost_notsecure/upload/_TEMP_/*")

      cmd = "decManageDB -d"
      ret = system(cmd)

      cmd = "decManageDB -c"
      ret = system(cmd)

      cmd = "decConfigInterface2DB -p EXTERNAL"
      ret = system(cmd)

      cmd = "decValidateConfig -a"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)   
   
      cmd = "decCheckConfig -e LOCALHOST_FTP"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      checkDirectory("/tmp/dec_delivery_root/GIP_PROBA2")
      
      sourceDir = DEC::ReadConfigDEC.instance.getSourceDir
      
      checkDirectory(sourceDir)
      puts "SOURCE DIR => #{sourceDir}"

      outTray     = "/tmp/dec_delivery_root"
      checkDirectory(outTray)

      1.upto(numFiles) do |i|
         filename = "test_ftp_#{i}.bin"
         cmd = "dd if=/dev/urandom of=#{outTray}/#{filename} bs=1024 count=#{numBlocks}"
         @@logger.debug(cmd)
         system(cmd)
      end

      cmd = "decGetFiles4Transfer"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "decSend2Interface --mnemonic LOCALHOST_FTP -O"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "decListDirUpload -m LOCALHOST_FTP -t"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      puts      

      cmd = "decStats"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      arr = Dir["/tmp/DEC*.log"]
     
      cmd = "cp #{arr[0]} /tmp/test_push_ftp_#{label}.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/dec_simul_if/localhost_notsecure/upload/test_ftp_*.bin"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END #{label}")

   end
   ## ------------------------------------------------------



end

### ==================================================================
