#!/usr/bin/env ruby

#########################################################################
#
# === Ruby source for #DEC_TestCases class
#
# === Written by DEIMOS Space S.L. (bolf)
#
# === Data Exchange Component
# 
# module DEC
#
#########################################################################

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'ctc/FTPClientCommands'
require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'
require 'dec/ReadInterfaceConfig'
require 'dec/ReadConfigOutgoing'
require 'dec/ReadConfigIncoming'

# Preconditions:
# 1 - setup 
# 1.1 - load_config_development
# 1.2 - inventory database is created

# 2 - teardown
# 2.1 - purge archive
# 2.2 - inventory database is destroyed

#  1  - test_decConfigInterface2DB
#  2  - test_decGetFromInterface
#  3  - test_decListener


# Select a single test of the suite

# ruby decUnitTests -n test_my_method 

# Start FTP Server in MacOS Sierra
# launchctl load -w /System/Library/LaunchDaemons/ftp.plist

# Stop FTP Server
# launchctl unload -w /System/Library/LaunchDaemons/ftp.plist

class DECTestCase < Test::Unit::TestCase

   include CUC::DirUtils
   include CTC::FTPClientCommands
   include DEC

   
   # Order of the test cases execution according to defintion within code
   self.test_order = :defined
   
   @my_argv = ARGV.dup
   
   ## ------------------------------------------------------
   
   Test::Unit.at_start do      
      puts
      puts "======================================"
      puts "DEC Unit Test Cases"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   
      
            @@arrDownloadFiles = [ \
                           "finals.all", \
                           "gpsrapid.out" \
                           ]

      
=begin
      puts
      puts
      puts "THINK IT TWICE  !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      c = STDIN.getc
            
      
      if c != 'Y' then
         exit(99)
      end

=end      
      
      @@conf = DEC_Environment.new
      
      @@conf.wrapper_load_config_development


      puts      
      @@conf.wrapper_print_environment
      puts
      
      
      @@conf.createEnvironmentDirs


      if @@conf.wrapper_check_environment == false then
         puts "DEC environment not suited for unit tests"
         puts
         exit(99)
      end
      
      
   end
   
   ## ------------------------------------------------------
   
   Test::Unit.at_exit do
      puts "End of DEC test for IERS interface"
   end
   
   ## ------------------------------------------------------
   
   ## Setup before every test-case
   ##
   def setup
      puts __method__.to_s
      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts
      
      @@conf.wrapper_load_config_development
            
      decConfig   = DEC::ReadConfigDEC.instance
      reportDir   = decConfig.getReportDir

      system("\\rm -rf #{reportDir}")
      system("\\rm -rf /tmp/dec*")
      system("\\rm -rf /tmp/DEC*.log")

      ftConfig    = ReadInterfaceConfig.instance
      configOut   = ReadConfigOutgoing.instance
      configIn    = ReadConfigIncoming.instance
      arrEnts     = ftConfig.getAllMnemonics

      arrEnts.each{|x|
                  
         bEnabled4Send  = ftConfig.isEnabled4Sending?(x)
         bEnabled4Recv  = ftConfig.isEnabled4Receiving?(x)

         ## --------------------------------------

         if bEnabled4Send == true then
         
            uploadDir = configOut.getUploadDir(x)
         
            if uploadDir == nil or uploadDir == "" then
               next
            end
         
            if uploadDir[0,1] != '/' then
               uploadDir = '~/' + uploadDir
            end
            checkDirectory(uploadDir)

            uploadTemp = configOut.getUploadTemp(x)
         
            if uploadTemp[0,1] != '/' then
               uploadTemp = '~/' + uploadTemp
            end
            checkDirectory(uploadTemp)
         end

         ## --------------------------------------

         if bEnabled4Recv == true then
            arr = configIn.getDownloadDirs(x)
            
            arr.each{|dir|
               
               downloadDir = ""

               if dir[:directory][0,1] != '/' then
                  downloadDir = '~/' + dir[:directory]
               else
                  downloadDir = dir[:directory]
               end
               
               # checkDirectory(downloadDir)
            }
            
#            ## create the files available for pulling
#            
#            if x.upcase.include?("LOCALHOST") or x.upcase.include?("FILESYSTEM") then
#               @@arrDownloadFiles.each{|filename|
#                  puts "#{filename}    => #{arr[0][:directory]}/#{filename}"
#                  system("echo \'#{filename}\' > #{arr[0][:directory]}/#{filename}")
#               }
#            end
            
         end

         ## --------------------------------------
      }
      
      
      cmd = "decManageDB -c"
      ret = system(cmd)
      
      if ret == false then
         puts
         puts "Error when creating the DEC inventory ! :-("
         puts
         # exit(99)
      end
      
      cmd = "decConfigInterface2DB -p EXTERNAL"
      
      ret = system(cmd)
      
      if ret == false then
         puts
         puts "Error when adding interface configuration to the database ! :-("
         puts
         # exit(99)
      end
      
   end
   ## --------------------------------------------------------
   ## After every test case

   def teardown
      puts __method__.to_s
      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts

      @@conf.wrapper_load_config_development

      cmd = "decManageDB -d"
      puts cmd
      ret = system(cmd)
       
      if ret == false then
         puts "Error when dropping the dec inventory ! :-("
         puts
         exit(99)
      end
   end
   ## ------------------------------------------------------

   ## ------------------------------------------------------

#   data("1",     ["ILRS",  false])
   data("2",     ["NOAA",  false])
#   data("3",     ["IERS",  false])
#   data("4",     ["IGS",   false])
#   data("5",     ["LEAP",  true])

   def test_ADP(params)

      interface, noDB = params
   
      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s} => #{interface} noDB #{noDB}"
      puts

      @@conf.wrapper_load_config_development

      puts
      puts
      @@conf.print_environment
      puts
      puts

      cmd = "decConfigInterface2DB -p EXTERNAL"
      assert(system(cmd), "decConfigInterface2DB --process EXTERNAL")

      @entityConfig     = ReadInterfaceConfig.instance
      conf              = ReadConfigIncoming.instance
      
      @finalDir         = conf.getIncomingDir(interface)
            
      checkDirectory(@finalDir)
      
      cmd = "decGetFromInterface -D -m #{interface} -l"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)

      cmd = "decGetFromInterface -m #{interface}"
      if noDB == true then
         cmd = "#{cmd} --nodb"
      end      
      puts cmd
      assert(system(cmd), cmd)      

      sleep(5.0)


      cmd = "decGetFromInterface -m #{interface} --no-intray"
      if noDB == true then
         cmd = "#{cmd} --nodb"
      end
      puts cmd
      assert(system(cmd), cmd)


      
   end
   ## ------------------------------------------------------

   ## Test to publish IERS Bulletin C Leap Second

   def test_ADP_S3

      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts

      checkDirectory(ReadConfigIncoming.instance.getIncomingDir("LEAP"))
      checkDirectory(ReadConfigIncoming.instance.getIncomingDir("PUBLISH_S3"))
      
      ReadConfigIncoming.instance.getDownloadDirs("PUBLISH_S3").each do |dir|
         checkDirectory(dir[:directory])
      end

      cmd = "decGetFromInterface -m LEAP -l"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)

      cmd = "decGetFromInterface -m LEAP --nodb"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)

      cmd = "decGetFromInterface -m PUBLISH_S3 -l"
      puts cmd
      assert(system(cmd), cmd)      

      cmd = "decGetFromInterface -m PUBLISH_S3"
      puts cmd
      assert(system(cmd), cmd)      

      file = "/tmp/dec_final_dissemination/S3/S3__GN_1_LSC_AX_*"
      
      arr = Dir["#{file}"]
      
      assert(File.exist?(arr[0]), "S3__GN_1_LSC_AX Downloaded")

      cmd = "decGetFromInterface -m LEAP --nodb"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)

      cmd = "decGetFromInterface -m PUBLISH_S3 -l"
      puts cmd
      assert(system(cmd), cmd)      

      cmd = "decGetFromInterface -m PUBLISH_S3"
      puts cmd
      assert(system(cmd), cmd)      
      
      arr = Dir["/tmp/DEC*.log"]
            
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 
   
   end
   ## ------------------------------------------------------

   ## Test to publish IERS Bulletin C Leap Second

   def test_ADP_S3_2

      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts

      checkDirectory(ReadConfigIncoming.instance.getIncomingDir("IGS"))
      checkDirectory(ReadConfigIncoming.instance.getIncomingDir("IERS"))
      checkDirectory(ReadConfigIncoming.instance.getIncomingDir("PUBLISH_S3"))
      
      ReadConfigIncoming.instance.getDownloadDirs("PUBLISH_S3").each do |dir|
         checkDirectory(dir[:directory])
      end

      system("rm -rf /tmp/dec_final_dissemination/S3")
      system("rm -rf /tmp/dec_final_dissemination/archive")
      system("rm -rf /tmp/dec_local_dissemination/S3")

#      cmd = "decGetFromInterface -m IGS -l"
#      puts cmd
#      assert(system(cmd), cmd)
#
#      sleep(5.0)
#

      cmd = "decGetFromInterface -m IERS"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)


      cmd = "decGetFromInterface -m IGS"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)


      cmd = "decGetFromInterface -m NOAA"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)


#      cmd = "decGetFromInterface -m LEAP --nodb"
#      puts cmd
#      assert(system(cmd), cmd)
#
#      sleep(5.0)

#      cmd = "decGetFromInterface -m PUBLISH_S3 -l"
#      puts cmd
#      assert(system(cmd), cmd)      

      cmd = "decGetFromInterface -m PUBLISH_S3"
      puts cmd
      assert(system(cmd), cmd)      

      puts
      puts
      cmd = "decStats -H 1"
      puts cmd
      assert(system(cmd), cmd)
      
      arr = Dir["/tmp/DEC*.log"]
            
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 

   
   end

   ## ------------------------------------------------------

   ## Pull circulation which upon disseminatin is chaining a push circulation 

   def test_IGS2POD
      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts
   
      checkDirectory("/tmp/http_put/pod")
      checkDirectory("/tmp/dec/if_igs_in_basket")
      
      cmd = "decGetFromInterface -m IGS"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)
      
      arr = Dir["/tmp/DEC*.log"]
                        
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 

   
   end
   ## ------------------------------------------------------

   def test_SCIHUB
      puts
      puts "================================================"
      puts "DEC_UnitTests::#{__method__.to_s}"
      puts
         
      system("rm -f /tmp/dec_final_dissemination/DIAS/*")
      
      cmd = "decGetFromInterface -m SCIHUB -l"
      puts cmd
      assert(system(cmd), cmd)

      cmd = "decGetFromInterface -m SCIHUB"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)

      cmd = "decGetFromInterface -m SCIHUB"
      puts cmd
      assert(system(cmd), cmd)

      sleep(5.0)      
      
      arr = Dir["/tmp/DEC*.log"]
                        
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}")   
   end
   ## ------------------------------------------------------

end


## ===================================================================




